name: r8q Build

# Controls when the action will run. Allows the workflow to be triggered manually via the GitHub Actions UI
on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Enter the device name (e.g., r8q)'
        required: true
        default: 'r8q'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Image Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          sudo dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get -y install build-essential uuid-dev clang llvm iasl nasm gcc-aarch64-linux-gnu abootimg python3-distutils python3-pil python3-git gettext libgcc-s1:i386 libstdc++6:i386
          sudo apt-get install --install-recommends winehq-stable

      - name: Build an image for ${{ github.event.inputs.device }}
        run: |
          ./build.sh --device ${{ github.event.inputs.device }} -f

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with: # Artifact name
          name: ${{ github.event.inputs.device }}
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.img
